- Job:
    name: "spc_rawdata.trigger_ah"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.trigger_car"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.trigger_dan"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.trigger_cta"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.trigger_files"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.trigger_kc"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.trigger_lfn"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.trigger_pit"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.trigger_qb"
    sla_time: "06:02"
- Job:
    name: "spc_rawdata.ah"
    sla_time: "06:40"
- Job:
    name: "spc_rawdata.car"
    sla_time: "06:45"
- Job:
    name: "spc_rawdata.cta"
    sla_time: "06:40"
- Job:
    name: "spc_rawdata.dan"
    sla_time: "06:51"
- Job:
    name: "spc_rawdata.files"
    sla_time: "06:30"
- Job:
    name: "spc_rawdata.kc"
    sla_time: "06:40"
- Job:
    name: "spc_rawdata.pit"
    sla_time: "07:19"
- Job:
    name: "spc_rawdata.qb"
    sla_time: "06:50"
- Job:
    name: "error_handler.truncate"
    sla_time: "07:21"
- Job:
    name: "rds_curated_data.dim_ytd"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_date"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_trip"
    sla_time: "08:13"
- Job:
    name: "rds_curated_data.dim_user"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_payor"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.fact_trip"
    sla_time: "08:46"
- Job:
    name: "rds_curated_data.dim_action"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_charge"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_credit"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_remark"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_patient"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_vehicle"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.stg_trip_qb"
    sla_time: "08:14"
- Job:
    name: "rds_curated_data.stg_trip_rn"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.stg_user_ad"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_modifier"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_priority"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_call_type"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_diagnosis"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_trip_demo"
    sla_time: "09:30"
- Job:
    name: "rds_curated_data.stg_agency_qb"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_payor_demo"
    sla_time: "09:32"
- Job:
    name: "rds_curated_data.dim_trip_stage"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.fact_trip_demo"
    sla_time: "09:33"
- Job:
    name: "rds_curated_data.finish_curated"
    sla_time: "09:29"
- Job:
    name: "rds_curated_data.stg_remarks_qb"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_charge_demo"
    sla_time: "09:29"
- Job:
    name: "rds_curated_data.dim_credit_demo"
    sla_time: "09:30"
- Job:
    name: "rds_curated_data.stg_trip_credit"
    sla_time: "08:32"
- Job:
    name: "rds_curated_data.dim_aging_bucket"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_company_demo"
    sla_time: "08:13"
- Job:
    name: "rds_curated_data.dim_patient_demo"
    sla_time: "09:31"
- Job:
    name: "rds_curated_data.dim_vehicle_demo"
    sla_time: "09:30"
- Job:
    name: "rds_curated_data.fact_trip_action"
    sla_time: "09:30"
- Job:
    name: "rds_curated_data.fact_trip_charge"
    sla_time: "08:54"
- Job:
    name: "rds_curated_data.fact_trip_credit"
    sla_time: "09:10"
- Job:
    name: "rds_curated_data.fact_trip_denial"
    sla_time: "08:23"
- Job:
    name: "rds_curated_data.stg_business_day"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_accident_type"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_denial_reason"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_priority_demo"
    sla_time: "09:31"
- Job:
    name: "rds_curated_data.dim_source_system"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.dim_call_type_demo"
    sla_time: "09:29"
- Job:
    name: "rds_curated_data.stg_mileage_charge"
    sla_time: "08:23"
- Job:
    name: "rds_curated_data.stg_pre_payment_qb"
    sla_time: "08:10"
- Job:
    name: "rds_curated_data.stg_trip_credit_qb"
    sla_time: "08:14"
- Job:
    name: "rds_curated_data.stg_trip_credit_rn"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.finish_curated_demo"
    sla_time: "09:34"
- Job:
    name: "rds_curated_data.stg_fee_schedule_qb"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_billing_schedule"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_calendar_holiday"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.map_closing_calendar"
    sla_time: "08:10"
- Job:
    name: "rds_curated_data.stg_base_rate_charge"
    sla_time: "08:23"
- Job:
    name: "rds_curated_data.fact_trip_charge_demo"
    sla_time: "09:32"
- Job:
    name: "rds_curated_data.fact_trip_credit_demo"
    sla_time: "09:33"
- Job:
    name: "rds_curated_data.fact_trip_denial_demo"
    sla_time: "09:33"
- Job:
    name: "rds_curated_data.log_etl_build_history"
    sla_time: "13:01"
- Job:
    name: "rds_curated_data.stg_claim_invoices_qb"
    sla_time: "08:10"
- Job:
    name: "rds_curated_data.stg_trip_credit_final"
    sla_time: "08:54"
- Job:
    name: "rds_curated_data.dim_denial_reason_demo"
    sla_time: "09:31"
- Job:
    name: "rds_curated_data.stg_claim_procedure_qb"
    sla_time: "07:56"
- Job:
    name: "rds_curated_data.finish_curated_dim_demo"
    sla_time: "09:32"
- Job:
    name: "rds_curated_data.stg_map_closing_calendar"
    sla_time: "08:10"
- Job:
    name: "rds_curated_data.dim_billing_schedule_demo"
    sla_time: "09:29"
- Job:
    name: "rds_curated_data.dim_company_profit_center"
    sla_time: "08:10"
- Job:
    name: "rds_curated_data.log_action_user_exception"
    sla_time: "09:45"
- Job:
    name: "rds_curated_data.stg_company_profit_center"
    sla_time: "08:00"
- Job:
    name: "rds_curated_data.dim_estimated_reimbursement"
    sla_time: "09:39"
- Job:
    name: "rds_curated_data.fact_profit_center_reporting"
    sla_time: "08:13"
- Job:
    name: "rds_curated_data.stg_map_closing_calendar_raw"
    sla_time: "08:05"
- Job:
    name: "rds_curated_data.dim_company_profit_center_demo"
    sla_time: "09:30"
- Job:
    name: "rds_curated_data.stg_est_reimb_by_primary_payor"
    sla_time: "09:37"
- Job:
    name: "rds_curated_data.stg_est_reimb_by_payor_level_one"
    sla_time: "09:36"
- Job:
    name: "rds_curated_data.stg_est_reimb_by_payor_level_two"
    sla_time: "09:36"
- Job:
    name: "rds_curated_data.stg_est_reimb_by_company_and_primary_payor"
    sla_time: "09:34"
- Job:
    name: "rds_curated_data.stg_est_reimb_by_company_and_payor_level_one"
    sla_time: "09:36"
- Job:
    name: "rds_curated_data.stg_est_reimb_by_company_and_payor_level_two"
    sla_time: "09:36"
- Job:
    name: "rds_curated_data.bridge_custom_company_charge"
    sla_time: "07:50"
- Job:
    name: "rds_curated_data.bridge_custom_company_credit"
    sla_time: "07:50"
- Job:
    name: "rds_curated_data.bridge_patient_insurance"
    sla_time: "07:55"
- Job:
    name: "rds_curated_data.dim_invoice_action"
    sla_time: "07:30"
- Job:
    name: "rds_curated_data.dim_invoice_status"
    sla_time: "07:30"
- Job:
    name: "rds_curated_data.dim_issue_reason"
    sla_time: "07:30"
- Job:
    name: "rds_curated_data.dim_issue_status"
    sla_time: "07:30"
- Job:
    name: "rds_curated_data.dim_jobs_hanger"
    sla_time: "13:10"
- Job:
    name: "rds_curated_data.dim_tag"
    sla_time: "07:30"
- Job:
    name: "rds_curated_data.fact_jobs_builds_hanger"
    sla_time: "13:10"
- Job:
    name: "rds_curated_data.fact_trip_action_demo"
    sla_time: "09:45"
- Job:
    name: "rds_curated_data.fact_trip_bto"
    sla_time: "08:40"
- Job:
    name: "rds_curated_data.fact_trip_bto_demo"
    sla_time: "09:40"
- Job:
    name: "rds_curated_data.fact_trip_invoice"
    sla_time: "08:40"
- Job:
    name: "rds_curated_data.fact_trip_invoice_demo"
    sla_time: "09:40"
- Job:
    name: "rds_curated_data.log_notification_exception"
    sla_time: "10:40"
- Job:
    name: "rds_curated_data.stg_claim_tags_qb"
    sla_time: "07:50"
- Job:
    name: "rds_curated_data.stg_trip_action"
    sla_time: "09:45"
- Job:
    name: "rds_aggregated_data.agg_trip"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_cpaag"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_rpaag"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_action"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_charge"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_credit"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_denial"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_bto"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_charge_detail"
    sla_time: "11:05"
- Job:
    name: "rds_aggregated_data.agg_trip_core_performance"
    sla_time: "11:05"
- Job:
    name: "rds_curated_data.log_etl_build"
    sla_time: "11:10"